# Generated by Django 2.1.1 on 2018-09-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='videos',
            field=models.ManyToManyField(related_name='categories', to='main.Video'),
        ),
    ]
