# Generated by Django 2.1.1 on 2018-10-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181008_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='techrole',
        ),
    ]
