# Generated by Django 2.1.1 on 2018-09-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Func',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('videos', models.ManyToManyField(related_name='videos', to='main.Video')),
            ],
        ),
    ]
