# Generated by Django 2.1.1 on 2018-10-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_category_techrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='techrole',
            field=models.BooleanField(null=True),
        ),
    ]
