# Generated by Django 2.1.1 on 2018-09-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_func'),
    ]

    operations = [
        migrations.AlterField(
            model_name='func',
            name='videos',
            field=models.ManyToManyField(related_name='funcs', to='main.Video'),
        ),
    ]
