# Generated by Django 2.1.1 on 2018-10-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='submitted_videos',
            field=models.ManyToManyField(related_name='_video_submitted_videos_+', to='main.Video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='remote',
            field=models.BooleanField(default=False),
        ),
    ]
