# Generated by Django 2.1.1 on 2018-09-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_video_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_file',
            new_name='file',
        ),
    ]
