# Generated by Django 2.1.1 on 2018-10-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181010_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submitted_video',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='submitted_videos',
        ),
        migrations.AddField(
            model_name='video',
            name='submitted_videos1',
            field=models.ManyToManyField(related_name='submitted_to', to='main.Video'),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
