# Generated by Django 2.1.1 on 2018-09-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_video_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='func',
            name='videos',
        ),
        migrations.AddField(
            model_name='video',
            name='categories',
            field=models.ManyToManyField(related_name='videos', to='main.Category'),
        ),
        migrations.AddField(
            model_name='video',
            name='funcs',
            field=models.ManyToManyField(related_name='videos', to='main.Func'),
        ),
    ]
