# Generated by Django 2.1.1 on 2018-09-23 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_auto_20180923_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='savers',
            field=models.ManyToManyField(related_name='saved_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
