# Generated by Django 2.1.1 on 2018-09-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_video_savers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Jobtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='experiences',
            field=models.ManyToManyField(related_name='videos', to='main.Experience'),
        ),
        migrations.AddField(
            model_name='video',
            name='jobtypes',
            field=models.ManyToManyField(related_name='videos', to='main.Jobtype'),
        ),
    ]
