# Generated by Django 2.1.1 on 2018-10-10 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_video_submitted_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateField()),
                ('submitted_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_video', to='main.Video')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='main.Video')),
            ],
        ),
    ]
