# Generated by Django 2.1.1 on 2018-10-10 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submitted_video',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='video',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
