# Generated by Django 2.1.1 on 2018-09-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180926_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='func',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
