# Generated by Django 2.1.1 on 2018-10-10 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20181010_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='submitted_videos',
            field=models.ManyToManyField(related_name='submitted_to', to='main.Video'),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_video', to='main.Video'),
        ),
        migrations.AddField(
            model_name='submission',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='main.Video'),
        ),
    ]
