# Generated by Django 2.1.1 on 2018-10-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20181010_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='submitted_videos',
            new_name='submitted_videos1',
        ),
    ]
