# Generated by Django 2.1.1 on 2018-10-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20181010_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submitted_video',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='submitted_videos1',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
