# Generated by Django 2.1.1 on 2018-10-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20181010_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='submitted_videos',
            field=models.ManyToManyField(related_name='submitted_to', to='main.Video'),
        ),
    ]
